apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-statefulset-flicker
  namespace: kubeeventjava
  labels:
    app: test-statefulset-flicker
spec:
  serviceName: test-statefulset-flicker
  replicas: 2
  selector:
    matchLabels:
      app: test-statefulset-flicker
  template:
    metadata:
      labels:
        app: test-statefulset-flicker
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: test
          image: busybox:1.36
          command: ["sh", "-c", "echo 'statefulset flicker starting'; sleep 10; echo 'statefulset flicker failing'; exit 1"]
          resources:
            requests:
              cpu: "10m"
              memory: "16Mi"
            limits:
              cpu: "50m"
              memory: "32Mi"
