apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-fail
  namespace: kubeeventjava
  labels:
    app: test-job-fail
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: test-job-fail
    spec:
      restartPolicy: OnFailure
      containers:
        - name: test
          image: busybox:1.36
          command: ["sh", "-c", "echo 'job failing intentionally'; exit 1"]
          resources:
            requests:
              cpu: "10m"
              memory: "16Mi"
            limits:
              cpu: "50m"
              memory: "32Mi"
